### ISSUE TITLE
[OTH issues] listing fee issue

### ISSUE THREAD

**Issue by dudezmobi** [KomodoPlatform/atomicDEX#103]
logging this in behalf of Carsen#3333

"It does just really really sucks for us smaller cap cryptos that have been hard at work for the past two + years that dont get funding like that
Just a big slap in the face"

You need to work with people in this space instead of cutting them off because they dont want to pay your $6.5k fee

**Comment by carsenk** [comment]
Thanks @dudezmobi 

To sum it up.

Cost to a developer to list their cryptocurrency on the atomicDEX GUI = $6,500.00 USD

Funding paid to a developer to develop a real cryptocurrency without an ICO = $0 USD

Cost of setting up and maintaining an SPV electrumx server = Roughly $5-10 USD per month

Cost of setting up integration with atomicGUI with a cryptocurrency already operating on the underlying layer MM2 / jl777/COINS repo = Maybe a few hours if that of "work"

The price just does not justify the cost at all, especially to those of us developers that contribute work for free and have no funding/ICO.

We as developers should not be punished/have to pay the price to be listed, Bitcoin and Litecoin were listed for free, why should we have to pay?

**Comment by ca333** [comment]
For sake of transparency and to provide some background info:

<img width="850" alt="Screenshot 2019-10-04 at 23 59 10" src="https://user-images.githubusercontent.com/10762374/66242935-fbaed280-e702-11e9-902f-84830e534f22.png">
<img width="817" alt="Screenshot 2019-10-04 at 23 56 46" src="https://user-images.githubusercontent.com/10762374/66242791-ae326580-e702-11e9-893a-108dda51b843.png">
<img width="827" alt="Screenshot 2019-10-04 at 23 57 00" src="https://user-images.githubusercontent.com/10762374/66242799-b12d5600-e702-11e9-8def-20dadb468a2e.png">

Conclusion:

We can't offer the mobile application service for free since we have a dedicated team to pay and 6500 USD is very fair - don't forget the devs behind the atomicDEX app, the support team and infrastructure admins, the DEX and SPV servers maintenance, and and and - these are all things that we have to pay for. And its really not cheap. Without charging for certain services we wouldn't be able to offer such an A+ end user product. However - the DEX core technology is as aforementioned open-source and completely free. We are not charging anything for that and my offer still stands to support you on that end if you re interested in building something on top of it.

**Comment by carsenk** [comment]
lol, this issue is certainly not resolved.
