### ISSUE TITLE
[Discussion] - Orders should be display as cumulated in the order book

### ISSUE THREAD

**Issue by nymkappa** [KomodoPlatform/atomicDEX#66]
## Issue
There are two orders for swapping 1 RICK to 0.5 MORTY. Those two orders should be accumulated in a single entry like a centralized exchange order book.

## Step to reproduce
1. Open the `Exchange` view
2. Set to exchange to 1 RICK
3. Choose to swap for MORTY. The order book will show the following
<img src="https://user-images.githubusercontent.com/9780671/62255617-ebdfed00-b438-11e9-99ad-f144b89e987b.jpg" alt="drawing" width="200"/>

## Issue
Both lines (inside the red area) should be merge into a single one, allowing me to place a "Market order".

## Note
This would only be good if a "Market buy" feature is implemented.
![image](https://user-images.githubusercontent.com/9780671/62255896-3150ea00-b43a-11e9-82c3-8ff6407f7bbf.png)

**Comment by tonymorony** [comment]
Clue is that on CEX by one "buy" action you can fill orders of N sellers, but in DEX your trade performing with one seller only at a time. As I see some additional logic on GUI side is needed to implement trading mechanism similar to what you explaining. If there are two 900 and 900 volume orders, to buy lets say 1100 at once you'll need two swaps actually with first seller and second one what will require double taker fees, tx fees + part of the swap might fail and interface should handle it as well. So a lot of additional logic is needed from my point of view with not very clear benefits on this point.

**Comment by jorisvial** [comment]
I definitely agree with `So a lot of additional logic is needed`. But I believe this is pure front-end logic.
Maybe the protocol itself could offer such functionality in the future as well.

*I actually believe the benefits would be great for low liquidity markets.*
For high liquidity market it would not really matter.

**Comment by ca333** [comment]
exactly - with the difference that we should not limit the required modifications on the GUI side since all trade-related operations are handled on the atomicDEX-API layer (backend). Although it could be implemented on the frontend, a backend implementation would make more sense and resolve this more efficiently since all GUIs and even CLI traders could profit from this. However, it does sound much like a future feature request for mm2 OR a trading-bot implementation for atomicDEX mobile where the GUI is able to do auto-trades to reach pre-set targets, etc. such a target could be "Buying min. 20 000 KMD with N of cryptocurrency X or other FOMO setups and auto order filling".
